// Generated by PicoPixel.io — https://picopixel.io
#include "images.h"

#include "images/mist.c"
#include "images/cloudy.c"
#include "images/day_partial_cloud.c"
#include "images/fog.c"
#include "images/alert.c"
#include "images/night_full_moon_clear.c"
#include "images/overcast.c"
#include "images/rain.c"
#include "images/day_clear.c"
#include "images/thunder.c"
#include "images/snow.c"
#include "images/day_rain.c"
#include "images/rain_80x80.c"
const ext_img_desc_t images[13] = {
    { "mist", &mist },
    { "cloudy", &cloudy },
    { "day_partial_cloud", &day_partial_cloud },
    { "fog", &fog },
    { "alert", &alert },
    { "night_full_moon_clear", &night_full_moon_clear },
    { "overcast", &overcast },
    { "rain", &rain },
    { "day_clear", &day_clear },
    { "thunder", &thunder },
    { "snow", &snow },
    { "day_rain", &day_rain },
    { "rain_80x80", &rain_80x80 }
};
