// Generated by PicoPixel.io — https://picopixel.io
#include <string.h>

#include "screens.h"
#include "colors.h"
#include "images.h"
#include "fonts.h"
#include "actions.h"
#include "vars.h"
#include "styles.h"
#include "ui.h"

objects_t objects;
lv_obj_t *tick_value_change_obj;

void create_screen_screenluft() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screenluft = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
        lv_obj_set_style_bg_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND]), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labellufttitel
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labellufttitel = obj;
            lv_obj_set_pos(obj, 0, 6);
            lv_obj_set_size(obj, 240, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Luftqualität");
        }
        {
            // labelnameozon
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameozon = obj;
            lv_obj_set_pos(obj, 12, 51);
            lv_obj_set_size(obj, 80, 37);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Ozon");
        }
        {
            // labelnamepm10
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamepm10 = obj;
            lv_obj_set_pos(obj, 12, 99);
            lv_obj_set_size(obj, 97, 37);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "PM10");
        }
        {
            // labelnamepm25
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamepm25 = obj;
            lv_obj_set_pos(obj, 12, 146);
            lv_obj_set_size(obj, 97, 37);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "PM2.5");
        }
        {
            // labelozonwert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelozonwert = obj;
            lv_obj_set_pos(obj, 110, 55);
            lv_obj_set_size(obj, 62, 28);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "18");
        }
        {
            // labelpm10wert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelpm10wert = obj;
            lv_obj_set_pos(obj, 110, 102);
            lv_obj_set_size(obj, 62, 28);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "22");
        }
        {
            // labelpm25wert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelpm25wert = obj;
            lv_obj_set_pos(obj, 110, 149);
            lv_obj_set_size(obj, 62, 28);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "9");
        }
        {
            // labelnameaqi
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameaqi = obj;
            lv_obj_set_pos(obj, 12, 193);
            lv_obj_set_size(obj, 97, 37);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "AQI");
        }
        {
            // labelaqiwert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelaqiwert = obj;
            lv_obj_set_pos(obj, 110, 198);
            lv_obj_set_size(obj, 62, 28);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "35");
        }
        {
            // unitozon
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.unitozon = obj;
            lv_obj_set_pos(obj, 177, 55);
            lv_obj_set_size(obj, 60, 22);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "μg/m³");
        }
        {
            // unitpm10
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.unitpm10 = obj;
            lv_obj_set_pos(obj, 177, 105);
            lv_obj_set_size(obj, 60, 22);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "μg/m³");
        }
        {
            // unitpm25
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.unitpm25 = obj;
            lv_obj_set_pos(obj, 177, 150);
            lv_obj_set_size(obj, 60, 22);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "μg/m³");
        }
    }

    tick_screen_screenluft();
}

void tick_screen_screenluft() {
}


void create_screen_screenlager() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screenlager = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
    {
        lv_obj_t *parent_obj = obj;
        {
            // img_alert
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_alert = obj;
            lv_obj_set_pos(obj, 8, 8);
            lv_obj_set_size(obj, 80, 80);
            lv_img_set_src(obj, &alert);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_cloudy
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_cloudy = obj;
            lv_obj_set_pos(obj, 66, 8);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &cloudy);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_day_clear
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_day_clear = obj;
            lv_obj_set_pos(obj, 124, 8);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &day_clear);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_day_partial_cloud
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_day_partial_cloud = obj;
            lv_obj_set_pos(obj, 182, 8);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &day_partial_cloud);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_day_rain
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_day_rain = obj;
            lv_obj_set_pos(obj, 8, 66);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &day_rain);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_fog
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_fog = obj;
            lv_obj_set_pos(obj, 66, 66);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &fog);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_mist
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_mist = obj;
            lv_obj_set_pos(obj, 124, 66);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &mist);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_night_full_moon_clear
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_night_full_moon_clear = obj;
            lv_obj_set_pos(obj, 182, 66);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &night_full_moon_clear);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_overcast
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_overcast = obj;
            lv_obj_set_pos(obj, 8, 124);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &overcast);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_rain
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_rain = obj;
            lv_obj_set_pos(obj, 66, 124);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &rain);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_rain_80x80
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_rain_80x80 = obj;
            lv_obj_set_pos(obj, 124, 124);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &rain_80x80);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_zoom(obj, 128);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_snow
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_snow = obj;
            lv_obj_set_pos(obj, 182, 124);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &snow);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // img_thunder
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.img_thunder = obj;
            lv_obj_set_pos(obj, 8, 182);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &thunder);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
    }

    tick_screen_screenlager();
}

void tick_screen_screenlager() {
}


void create_screen_uiscreenwarnungpollen() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.uiscreenwarnungpollen = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(common_cc0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // imagewarnpollen
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.imagewarnpollen = obj;
            lv_obj_set_pos(obj, 75, 0);
            lv_obj_set_size(obj, 80, 80);
            lv_img_set_src(obj, &alert);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // labelpollenwarntitel
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelpollenwarntitel = obj;
            lv_obj_set_pos(obj, 0, 92);
            lv_obj_set_size(obj, 240, 34);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Pollenwarnung!");
        }
        {
            // labelpollenwarnart
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelpollenwarnart = obj;
            lv_obj_set_pos(obj, 0, 138);
            lv_obj_set_size(obj, 240, 22);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Birke: Hoch");
        }
        {
            // labelpollenwarnhint
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelpollenwarnhint = obj;
            lv_obj_set_pos(obj, 0, 174);
            lv_obj_set_size(obj, 240, 37);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Tippen zum Bestätigen");
        }
    }

    tick_screen_uiscreenwarnungpollen();
}

void tick_screen_uiscreenwarnungpollen() {
}


void create_screen_uiscreenwarnung() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.uiscreenwarnung = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
        lv_obj_set_style_bg_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(common_cc0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // imagewarnregen
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.imagewarnregen = obj;
            lv_obj_set_pos(obj, 80, 5);
            lv_obj_set_size(obj, 80, 80);
            lv_img_set_src(obj, &rain_80x80);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
        }
        {
            // labelwarntitel
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelwarntitel = obj;
            lv_obj_set_pos(obj, 0, 92);
            lv_obj_set_size(obj, 240, 34);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Regenwarnung!");
        }
        {
            // labelwarndetail
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelwarndetail = obj;
            lv_obj_set_pos(obj, 0, 127);
            lv_obj_set_size(obj, 240, 44);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Regen in den nächsten 60 Min.");
        }
        {
            // labelwarnhint
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelwarnhint = obj;
            lv_obj_set_pos(obj, 0, 191);
            lv_obj_set_size(obj, 240, 20);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Tippen zum Bestätigen");
        }
    }

    tick_screen_uiscreenwarnung();
}

void tick_screen_uiscreenwarnung() {
}


void create_screen_screenpollen() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screenpollen = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
        lv_obj_set_style_bg_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND]), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labelnamebirke
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamebirke = obj;
            lv_obj_set_pos(obj, 13, 51);
            lv_obj_set_size(obj, 70, 22);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Birke");
        }
        {
            // labelnamebeifuss
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamebeifuss = obj;
            lv_obj_set_pos(obj, 13, 156);
            lv_obj_set_size(obj, 89, 22);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Beifuss");
        }
        {
            // labelnamegraeser
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnamegraeser = obj;
            lv_obj_set_pos(obj, 13, 86);
            lv_obj_set_size(obj, 66, 22);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Gräser");
        }
        {
            // labelnameerle
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameerle = obj;
            lv_obj_set_pos(obj, 13, 121);
            lv_obj_set_size(obj, 51, 22);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Erle");
        }
        {
            // labelnameambrosia
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelnameambrosia = obj;
            lv_obj_set_pos(obj, 13, 191);
            lv_obj_set_size(obj, 89, 22);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Ambrosia");
        }
        {
            // labelbirkewert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelbirkewert = obj;
            lv_obj_set_pos(obj, 135, 51);
            lv_obj_set_size(obj, 101, 22);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "12");
        }
        {
            // labelgraeserwert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelgraeserwert = obj;
            lv_obj_set_pos(obj, 135, 86);
            lv_obj_set_size(obj, 101, 22);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "12");
        }
        {
            // labelambrosiawert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelambrosiawert = obj;
            lv_obj_set_pos(obj, 135, 191);
            lv_obj_set_size(obj, 101, 22);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "12");
        }
        {
            // labelbeifusswert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelbeifusswert = obj;
            lv_obj_set_pos(obj, 135, 156);
            lv_obj_set_size(obj, 101, 22);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "12");
        }
        {
            // labelerlewert
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelerlewert = obj;
            lv_obj_set_pos(obj, 135, 121);
            lv_obj_set_size(obj, 101, 22);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "12");
        }
        {
            // textareapollen
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.textareapollen = obj;
            lv_obj_set_pos(obj, 0, 6);
            lv_obj_set_size(obj, 240, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Pollenflug");
        }
    }

    tick_screen_screenpollen();
}

void tick_screen_screenpollen() {
}


void create_screen_screenboot() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screenboot = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
        lv_obj_set_style_bg_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND]), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labelwetter
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelwetter = obj;
            lv_obj_set_pos(obj, 30, 24);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Wetter");
        }
        {
            // labelcube
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelcube = obj;
            lv_obj_set_pos(obj, 131, 24);
            lv_obj_set_size(obj, 79, 34);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_87ceeb), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Cube");
        }
        {
            // labelauthor
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelauthor = obj;
            lv_obj_set_pos(obj, 32, 63);
            lv_obj_set_size(obj, 178, 20);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_aaaaaa), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "by Jan Althaus");
        }
        {
            // barwifi
            lv_obj_t *obj = lv_bar_create(parent_obj);
            objects.barwifi = obj;
            lv_obj_set_pos(obj, 20, 163);
            lv_obj_set_size(obj, 200, 10);
            lv_bar_set_range(obj, 0, 100);
            lv_bar_set_value(obj, 25, LV_ANIM_OFF);
        }
        {
            // labelstatus
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelstatus = obj;
            lv_obj_set_pos(obj, 0, 113);
            lv_obj_set_size(obj, 240, 33);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_808080), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Verbinde mit WLAN...");
        }
    }

    tick_screen_screenboot();
}

void tick_screen_screenboot() {
}


void create_screen_screen4() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen4 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
        lv_obj_set_style_bg_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND]), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // container1
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.container1 = obj;
            lv_obj_set_pos(obj, 12, 6);
            lv_obj_set_size(obj, 215, 69);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_side(obj, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        {
            // labelh1zeit
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelh1zeit = obj;
            lv_obj_set_pos(obj, 0, 28);
            lv_obj_set_size(obj, 79, 24);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "12:00");
        }
        {
            // imageh1
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.imageh1 = obj;
            lv_obj_set_pos(obj, 103, 23);
            lv_obj_set_size(obj, 35, 35);
            lv_img_set_src(obj, &rain);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_zoom(obj, 218);
            lv_img_set_antialias(obj, true);
        }
        {
            // labelh1temp
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelh1temp = obj;
            lv_obj_set_pos(obj, 164, 28);
            lv_obj_set_size(obj, 63, 28);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "15 °C");
        }
        {
            // container2
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.container2 = obj;
            lv_obj_set_pos(obj, 12, 82);
            lv_obj_set_size(obj, 215, 69);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        {
            // labelh2zeit
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelh2zeit = obj;
            lv_obj_set_pos(obj, 0, 106);
            lv_obj_set_size(obj, 79, 24);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "12:00");
        }
        {
            // imageh2
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.imageh2 = obj;
            lv_obj_set_pos(obj, 103, 100);
            lv_obj_set_size(obj, 35, 35);
            lv_img_set_src(obj, &day_partial_cloud);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_zoom(obj, 218);
            lv_img_set_antialias(obj, true);
        }
        {
            // labelh2temp
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelh2temp = obj;
            lv_obj_set_pos(obj, 164, 106);
            lv_obj_set_size(obj, 63, 28);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "15 °C");
        }
        {
            // container3
            lv_obj_t *obj = lv_obj_create(parent_obj);
            objects.container3 = obj;
            lv_obj_set_pos(obj, 12, 160);
            lv_obj_set_size(obj, 215, 69);
            lv_obj_clear_flag(obj, LV_OBJ_FLAG_SCROLLABLE);
            lv_obj_set_style_pad_all(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_radius(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_bg_opa(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_border_width(obj, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
        }
        {
            // labelh3zeit
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelh3zeit = obj;
            lv_obj_set_pos(obj, 0, 183);
            lv_obj_set_size(obj, 79, 24);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "12:00");
        }
        {
            // imageh3
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.imageh3 = obj;
            lv_obj_set_pos(obj, 103, 179);
            lv_obj_set_size(obj, 35, 35);
            lv_img_set_src(obj, &overcast);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_zoom(obj, 218);
            lv_img_set_antialias(obj, true);
        }
        {
            // labelh3temp
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelh3temp = obj;
            lv_obj_set_pos(obj, 164, 185);
            lv_obj_set_size(obj, 63, 28);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "15 °C");
        }
    }

    tick_screen_screen4();
}

void tick_screen_screen4() {
}


void create_screen_screen3() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen3 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
        lv_obj_set_style_bg_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND]), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labelaufgang
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelaufgang = obj;
            lv_obj_set_pos(obj, 1, 47);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "12:00");
        }
        {
            // labeluntergang
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeluntergang = obj;
            lv_obj_set_pos(obj, 1, 121);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "13:00");
        }
        {
            // labeluv
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeluv = obj;
            lv_obj_set_pos(obj, 1, 196);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "6");
        }
        {
            // textsonnenaufgang
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.textsonnenaufgang = obj;
            lv_obj_set_pos(obj, 1, 14);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Sonnenaufgang");
        }
        {
            // textsonnenuntergang
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.textsonnenuntergang = obj;
            lv_obj_set_pos(obj, 1, 88);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Sonnenaufgang");
        }
        {
            // textuv
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.textuv = obj;
            lv_obj_set_pos(obj, 1, 163);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "UV Index");
        }
    }

    tick_screen_screen3();
}

void tick_screen_screen3() {
}


void create_screen_screen2() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen2 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
        lv_obj_set_style_bg_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND]), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labelpress
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelpress = obj;
            lv_obj_set_pos(obj, 1, 47);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "1022 hPa");
        }
        {
            // labelfeelslike
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelfeelslike = obj;
            lv_obj_set_pos(obj, 1, 196);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "-1°C");
        }
        {
            // labelhum
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelhum = obj;
            lv_obj_set_pos(obj, 1, 121);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "58 %");
        }
        {
            // textarea3
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.textarea3 = obj;
            lv_obj_set_pos(obj, 1, 14);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Luftdruck");
        }
        {
            // textarea4
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.textarea4 = obj;
            lv_obj_set_pos(obj, 1, 88);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Luftfeuchtigkeit");
        }
        {
            // textarea5
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.textarea5 = obj;
            lv_obj_set_pos(obj, 1, 163);
            lv_obj_set_size(obj, 238, 27);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Gefühlt wie");
        }
    }

    tick_screen_screen2();
}

void tick_screen_screen2() {
}


void create_screen_screen1() {
    lv_obj_t *obj = lv_obj_create(0);
    objects.screen1 = obj;
    lv_obj_set_pos(obj, 0, 0);
    lv_obj_set_size(obj, 240, 240);
        lv_obj_set_style_bg_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_BACKGROUND]), LV_PART_MAIN | LV_STATE_DEFAULT);
    {
        lv_obj_t *parent_obj = obj;
        {
            // labeluhr
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeluhr = obj;
            lv_obj_set_pos(obj, 21, 18);
            lv_obj_set_size(obj, 198, 58);
            lv_obj_set_style_text_letter_space(obj, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_line_space(obj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "15:05");
        }
        {
            // labeltemp
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labeltemp = obj;
            lv_obj_set_pos(obj, 18, 186);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(common_ece0e0), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "22° C");
        }
        {
            // imagewetter
            lv_obj_t *obj = lv_img_create(parent_obj);
            objects.imagewetter = obj;
            lv_obj_set_pos(obj, 33, 135);
            lv_obj_set_size(obj, 40, 40);
            lv_img_set_src(obj, &day_clear);
            lv_img_set_size_mode(obj, LV_IMG_SIZE_MODE_REAL);
            lv_img_set_antialias(obj, true);
            lv_obj_add_flag(obj, LV_OBJ_FLAG_ADV_HITTEST);
        }
        {
            // uilabeldatum
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.uilabeldatum = obj;
            lv_obj_set_pos(obj, 0, 89);
            lv_obj_set_size(obj, 240, 34);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "Mi. 20.05.2026");
        }
        {
            // labelwind
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelwind = obj;
            lv_obj_set_pos(obj, 113, 186);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, "25 Km/h");
        }
        {
            // labelwinddir
            lv_obj_t *obj = lv_label_create(parent_obj);
            objects.labelwinddir = obj;
            lv_obj_set_pos(obj, 149, 138);
            lv_obj_set_size(obj, LV_SIZE_CONTENT, LV_SIZE_CONTENT);
            lv_obj_set_style_text_opa(obj, (lv_opa_t)(theme_colors[active_theme_index][THEME_COLOR_TEXT] >> 24), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_font(obj, &font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(obj, lv_color_hex(theme_colors[active_theme_index][THEME_COLOR_TEXT]), LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_obj_set_style_text_align(obj, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(obj, " N");
        }
    }

    tick_screen_screen1();
}

void tick_screen_screen1() {
}



typedef void (*tick_screen_func_t)();
tick_screen_func_t tick_screen_funcs[] = {
    tick_screen_screenluft,
    tick_screen_screenlager,
    tick_screen_uiscreenwarnungpollen,
    tick_screen_uiscreenwarnung,
    tick_screen_screenpollen,
    tick_screen_screenboot,
    tick_screen_screen4,
    tick_screen_screen3,
    tick_screen_screen2,
    tick_screen_screen1,
};
void tick_screen(int screen_index) {
    tick_screen_funcs[screen_index]();
}
void tick_screen_by_id(enum ScreensEnum screenId) {
    tick_screen_funcs[screenId - 1]();
}

void delete_screen_screenluft() {
    if (objects.screenluft != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screenluft);
        lv_obj_del(objects.screenluft);
    }
    objects.screenluft = 0;
    objects.labellufttitel = 0;
    objects.labelnameozon = 0;
    objects.labelnamepm10 = 0;
    objects.labelnamepm25 = 0;
    objects.labelozonwert = 0;
    objects.labelpm10wert = 0;
    objects.labelpm25wert = 0;
    objects.labelnameaqi = 0;
    objects.labelaqiwert = 0;
    objects.unitozon = 0;
    objects.unitpm10 = 0;
    objects.unitpm25 = 0;
}

void delete_screen_screenlager() {
    if (objects.screenlager != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screenlager);
        lv_obj_del(objects.screenlager);
    }
    objects.screenlager = 0;
    objects.img_alert = 0;
    objects.img_cloudy = 0;
    objects.img_day_clear = 0;
    objects.img_day_partial_cloud = 0;
    objects.img_day_rain = 0;
    objects.img_fog = 0;
    objects.img_mist = 0;
    objects.img_night_full_moon_clear = 0;
    objects.img_overcast = 0;
    objects.img_rain = 0;
    objects.img_rain_80x80 = 0;
    objects.img_snow = 0;
    objects.img_thunder = 0;
}

void delete_screen_uiscreenwarnungpollen() {
    if (objects.uiscreenwarnungpollen != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.uiscreenwarnungpollen);
        lv_obj_del(objects.uiscreenwarnungpollen);
    }
    objects.uiscreenwarnungpollen = 0;
    objects.imagewarnpollen = 0;
    objects.labelpollenwarntitel = 0;
    objects.labelpollenwarnart = 0;
    objects.labelpollenwarnhint = 0;
}

void delete_screen_uiscreenwarnung() {
    if (objects.uiscreenwarnung != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.uiscreenwarnung);
        lv_obj_del(objects.uiscreenwarnung);
    }
    objects.uiscreenwarnung = 0;
    objects.imagewarnregen = 0;
    objects.labelwarntitel = 0;
    objects.labelwarndetail = 0;
    objects.labelwarnhint = 0;
}

void delete_screen_screenpollen() {
    if (objects.screenpollen != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screenpollen);
        lv_obj_del(objects.screenpollen);
    }
    objects.screenpollen = 0;
    objects.labelnamebirke = 0;
    objects.labelnamebeifuss = 0;
    objects.labelnamegraeser = 0;
    objects.labelnameerle = 0;
    objects.labelnameambrosia = 0;
    objects.labelbirkewert = 0;
    objects.labelgraeserwert = 0;
    objects.labelambrosiawert = 0;
    objects.labelbeifusswert = 0;
    objects.labelerlewert = 0;
    objects.textareapollen = 0;
}

void delete_screen_screenboot() {
    if (objects.screenboot != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screenboot);
        lv_obj_del(objects.screenboot);
    }
    objects.screenboot = 0;
    objects.labelwetter = 0;
    objects.labelcube = 0;
    objects.labelauthor = 0;
    objects.barwifi = 0;
    objects.labelstatus = 0;
}

void delete_screen_screen4() {
    if (objects.screen4 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen4);
        lv_obj_del(objects.screen4);
    }
    objects.screen4 = 0;
    objects.container1 = 0;
    objects.labelh1zeit = 0;
    objects.imageh1 = 0;
    objects.labelh1temp = 0;
    objects.container2 = 0;
    objects.labelh2zeit = 0;
    objects.imageh2 = 0;
    objects.labelh2temp = 0;
    objects.container3 = 0;
    objects.labelh3zeit = 0;
    objects.imageh3 = 0;
    objects.labelh3temp = 0;
}

void delete_screen_screen3() {
    if (objects.screen3 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen3);
        lv_obj_del(objects.screen3);
    }
    objects.screen3 = 0;
    objects.labelaufgang = 0;
    objects.labeluntergang = 0;
    objects.labeluv = 0;
    objects.textsonnenaufgang = 0;
    objects.textsonnenuntergang = 0;
    objects.textuv = 0;
}

void delete_screen_screen2() {
    if (objects.screen2 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen2);
        lv_obj_del(objects.screen2);
    }
    objects.screen2 = 0;
    objects.labelpress = 0;
    objects.labelfeelslike = 0;
    objects.labelhum = 0;
    objects.textarea3 = 0;
    objects.textarea4 = 0;
    objects.textarea5 = 0;
}

void delete_screen_screen1() {
    if (objects.screen1 != NULL) {
        pp_anim_stop_timelines_for_deleted_tree(objects.screen1);
        lv_obj_del(objects.screen1);
    }
    objects.screen1 = 0;
    objects.labeluhr = 0;
    objects.labeltemp = 0;
    objects.imagewetter = 0;
    objects.uilabeldatum = 0;
    objects.labelwind = 0;
    objects.labelwinddir = 0;
}


typedef void (*delete_screen_func_t)();
delete_screen_func_t delete_screen_funcs[] = {
    delete_screen_screenluft,
    delete_screen_screenlager,
    delete_screen_uiscreenwarnungpollen,
    delete_screen_uiscreenwarnung,
    delete_screen_screenpollen,
    delete_screen_screenboot,
    delete_screen_screen4,
    delete_screen_screen3,
    delete_screen_screen2,
    delete_screen_screen1,
};
void delete_screen_by_id(enum ScreensEnum screenId) {
    delete_screen_funcs[screenId - 1]();
}

void create_screens() {
    lv_disp_t *dispp = lv_disp_get_default();
    // Use dark theme (true) to match the editor's appearance - white text on dark buttons
    lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    create_screen_screenluft();
    create_screen_screenlager();
    create_screen_uiscreenwarnungpollen();
    create_screen_uiscreenwarnung();
    create_screen_screenpollen();
    create_screen_screenboot();
    create_screen_screen4();
    create_screen_screen3();
    create_screen_screen2();
    create_screen_screen1();
}
