// Generated by PicoPixel.io — https://picopixel.io
#ifndef PICOPIXEL_LVGL_UI_SCREENS_H
#define PICOPIXEL_LVGL_UI_SCREENS_H

#include <lvgl.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _objects_t {
    lv_obj_t *screenlager;
    lv_obj_t *uiscreenwarnungpollen;
    lv_obj_t *uiscreenwarnung;
    lv_obj_t *screenpollen;
    lv_obj_t *screenboot;
    lv_obj_t *screen4;
    lv_obj_t *screen3;
    lv_obj_t *screen2;
    lv_obj_t *screen1;
    lv_obj_t *labeluhr;
    lv_obj_t *labeltemp;
    lv_obj_t *imagewetter;
    lv_obj_t *uilabeldatum;
    lv_obj_t *labelwind;
    lv_obj_t *labelwinddir;
    lv_obj_t *labelpress;
    lv_obj_t *labelfeelslike;
    lv_obj_t *labelhum;
    lv_obj_t *textarea3;
    lv_obj_t *textarea4;
    lv_obj_t *textarea5;
    lv_obj_t *labelaufgang;
    lv_obj_t *labeluntergang;
    lv_obj_t *labeluv;
    lv_obj_t *textsonnenaufgang;
    lv_obj_t *textsonnenuntergang;
    lv_obj_t *textuv;
    lv_obj_t *container1;
    lv_obj_t *labelh1zeit;
    lv_obj_t *imageh1;
    lv_obj_t *labelh1temp;
    lv_obj_t *container2;
    lv_obj_t *labelh2zeit;
    lv_obj_t *imageh2;
    lv_obj_t *labelh2temp;
    lv_obj_t *container3;
    lv_obj_t *labelh3zeit;
    lv_obj_t *imageh3;
    lv_obj_t *labelh3temp;
    lv_obj_t *labelwetter;
    lv_obj_t *labelcube;
    lv_obj_t *labelauthor;
    lv_obj_t *barwifi;
    lv_obj_t *labelstatus;
    lv_obj_t *labelnamebirke;
    lv_obj_t *labelnamebeifuss;
    lv_obj_t *labelnamegraeser;
    lv_obj_t *labelnameerle;
    lv_obj_t *labelnameambrosia;
    lv_obj_t *labelbirkewert;
    lv_obj_t *labelgraeserwert;
    lv_obj_t *labelambrosiawert;
    lv_obj_t *labelbeifusswert;
    lv_obj_t *labelerlewert;
    lv_obj_t *textareapollen;
    lv_obj_t *imagewarnregen;
    lv_obj_t *labelwarntitel;
    lv_obj_t *labelwarndetail;
    lv_obj_t *labelwarnhint;
    lv_obj_t *imagewarnpollen;
    lv_obj_t *labelpollenwarntitel;
    lv_obj_t *labelpollenwarnart;
    lv_obj_t *labelpollenwarnhint;
    lv_obj_t *img_alert;
    lv_obj_t *img_cloudy;
    lv_obj_t *img_day_clear;
    lv_obj_t *img_day_partial_cloud;
    lv_obj_t *img_day_rain;
    lv_obj_t *img_fog;
    lv_obj_t *img_mist;
    lv_obj_t *img_night_full_moon_clear;
    lv_obj_t *img_overcast;
    lv_obj_t *img_rain;
    lv_obj_t *img_rain_80x80;
    lv_obj_t *img_snow;
    lv_obj_t *img_thunder;
} objects_t;

extern objects_t objects;

enum ScreensEnum {
    SCREEN_ID_SCREENLAGER = 1,
    SCREEN_ID_UISCREENWARNUNGPOLLEN = 2,
    SCREEN_ID_UISCREENWARNUNG = 3,
    SCREEN_ID_SCREENPOLLEN = 4,
    SCREEN_ID_SCREENBOOT = 5,
    SCREEN_ID_SCREEN4 = 6,
    SCREEN_ID_SCREEN3 = 7,
    SCREEN_ID_SCREEN2 = 8,
    SCREEN_ID_SCREEN1 = 9,
};

void create_screen_screenlager();
void tick_screen_screenlager();
void delete_screen_screenlager();
void create_screen_uiscreenwarnungpollen();
void tick_screen_uiscreenwarnungpollen();
void delete_screen_uiscreenwarnungpollen();
void create_screen_uiscreenwarnung();
void tick_screen_uiscreenwarnung();
void delete_screen_uiscreenwarnung();
void create_screen_screenpollen();
void tick_screen_screenpollen();
void delete_screen_screenpollen();
void create_screen_screenboot();
void tick_screen_screenboot();
void delete_screen_screenboot();
void create_screen_screen4();
void tick_screen_screen4();
void delete_screen_screen4();
void create_screen_screen3();
void tick_screen_screen3();
void delete_screen_screen3();
void create_screen_screen2();
void tick_screen_screen2();
void delete_screen_screen2();
void create_screen_screen1();
void tick_screen_screen1();
void delete_screen_screen1();

void tick_screen_by_id(enum ScreensEnum screenId);
void tick_screen(int screen_index);

void delete_screen_by_id(enum ScreensEnum screenId);

void create_screens();


#ifdef __cplusplus
}
#endif

#endif /*PICOPIXEL_LVGL_UI_SCREENS_H*/
