// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#ifndef _WETTERKLEIN_UI_H
#define _WETTERKLEIN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_ScreenBoot.h"
#include "ui_Screen1.h"
#include "ui_Screen4.h"
#include "ui_ScreenLager.h"
#include "ui_Screen2.h"
#include "ui_Screen3.h"
#include "ui_uiScreenWarnung.h"
#include "ui_ScreenPollen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_day_clear_png);   // assets/day_clear.png
LV_IMG_DECLARE( ui_img_rain_png);   // assets/rain.png
LV_IMG_DECLARE( ui_img_thunder_png);   // assets/thunder.png
LV_IMG_DECLARE( ui_img_fog_png);   // assets/fog.png
LV_IMG_DECLARE( ui_img_overcast_png);   // assets/overcast.png
LV_IMG_DECLARE( ui_img_snow_png);   // assets/snow.png
LV_IMG_DECLARE( ui_img_rain_80x80_png);   // assets/rain_80x80.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
