// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#ifndef _UI_COMP_IMAGEWETTER_H
#define _UI_COMP_IMAGEWETTER_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ImageWetter
#define UI_COMP_IMAGEWETTER_IMAGEWETTER 0
#define _UI_COMP_IMAGEWETTER_NUM 1
lv_obj_t *ui_ImageWetter_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
