// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#include "ui.h"

// COMPONENT ImageWetter

lv_obj_t *ui_ImageWetter_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_ImageWetter;
cui_ImageWetter = lv_img_create(comp_parent);
lv_img_set_src(cui_ImageWetter, &ui_img_day_clear_png);
lv_obj_set_width( cui_ImageWetter, LV_SIZE_CONTENT);  /// 40
lv_obj_set_height( cui_ImageWetter, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( cui_ImageWetter, 0 );
lv_obj_set_y( cui_ImageWetter, 44 );
lv_obj_set_align( cui_ImageWetter, LV_ALIGN_CENTER );
lv_obj_add_flag( cui_ImageWetter, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( cui_ImageWetter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(cui_ImageWetter,40);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_IMAGEWETTER_NUM);
children[UI_COMP_IMAGEWETTER_IMAGEWETTER] = cui_ImageWetter;
lv_obj_add_event_cb(cui_ImageWetter, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_ImageWetter, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_ImageWetter_create_hook(cui_ImageWetter);
return cui_ImageWetter; 
}

