// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#ifndef UI_SCREENBOOT_H
#define UI_SCREENBOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenBoot
extern void ui_ScreenBoot_screen_init(void);
extern void ui_ScreenBoot_screen_destroy(void);
extern lv_obj_t *ui_ScreenBoot;
extern lv_obj_t *ui_LabelWetter;
extern lv_obj_t *ui_LabelCube;
extern lv_obj_t *ui_LabelAuthor;
extern lv_obj_t *ui_BarWifi;
extern lv_obj_t *ui_LabelStatus;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenBoot;
extern lv_obj_t *uic_LabelWetter;
extern lv_obj_t *uic_LabelCube;
extern lv_obj_t *uic_LabelAuthor;
extern lv_obj_t *uic_BarWifi;
extern lv_obj_t *uic_LabelStatus;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

