// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_LabelUhr;
extern lv_obj_t *ui_LabelTemp;
extern lv_obj_t *ui_ImageWetter;
extern lv_obj_t *ui_LabelHum;
extern lv_obj_t *ui_uiLabelDatum;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image2;
// CUSTOM VARIABLES
extern lv_obj_t *uic_LabelUhr;
extern lv_obj_t *uic_LabelTemp;
extern lv_obj_t *uic_ImageWetter;
extern lv_obj_t *uic_LabelHum;
extern lv_obj_t *uic_uiLabelDatum;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

