// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#include "ui.h"

lv_obj_t *uic_LabelStatus;
lv_obj_t *uic_BarWifi;
lv_obj_t *uic_LabelAuthor;
lv_obj_t *uic_LabelCube;
lv_obj_t *uic_LabelWetter;
lv_obj_t *uic_ScreenBoot;
lv_obj_t *ui_ScreenBoot = NULL;lv_obj_t *ui_LabelWetter = NULL;lv_obj_t *ui_LabelCube = NULL;lv_obj_t *ui_LabelAuthor = NULL;lv_obj_t *ui_BarWifi = NULL;lv_obj_t *ui_LabelStatus = NULL;
// event funtions

// build funtions

void ui_ScreenBoot_screen_init(void)
{
ui_ScreenBoot = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenBoot, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenBoot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenBoot, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWetter = lv_label_create(ui_ScreenBoot);
lv_obj_set_width( ui_LabelWetter, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWetter, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWetter, -39 );
lv_obj_set_y( ui_LabelWetter, -79 );
lv_obj_set_align( ui_LabelWetter, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWetter,"Wetter");
lv_obj_set_scrollbar_mode(ui_LabelWetter, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelWetter, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWetter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelWetter, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelWetter, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelCube = lv_label_create(ui_ScreenBoot);
lv_obj_set_width( ui_LabelCube, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelCube, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelCube, 50 );
lv_obj_set_y( ui_LabelCube, -79 );
lv_obj_set_align( ui_LabelCube, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelCube,"Cube");
lv_obj_set_scrollbar_mode(ui_LabelCube, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelCube, lv_color_hex(0x87CEEB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelCube, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelCube, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAuthor = lv_label_create(ui_ScreenBoot);
lv_obj_set_width( ui_LabelAuthor, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAuthor, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelAuthor, 0 );
lv_obj_set_y( ui_LabelAuthor, -47 );
lv_obj_set_align( ui_LabelAuthor, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAuthor,"by Jan Althaus");
lv_obj_set_scrollbar_mode(ui_LabelAuthor, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelAuthor, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelAuthor, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelAuthor, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarWifi = lv_bar_create(ui_ScreenBoot);
lv_bar_set_value(ui_BarWifi,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarWifi, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarWifi, 200);
lv_obj_set_height( ui_BarWifi, 10);
lv_obj_set_x( ui_BarWifi, 0 );
lv_obj_set_y( ui_BarWifi, 48 );
lv_obj_set_align( ui_BarWifi, LV_ALIGN_CENTER );

ui_LabelStatus = lv_label_create(ui_ScreenBoot);
lv_obj_set_width( ui_LabelStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStatus, 0 );
lv_obj_set_y( ui_LabelStatus, 12 );
lv_obj_set_align( ui_LabelStatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStatus,"Verbinde mit WLAN...");
lv_obj_set_scrollbar_mode(ui_LabelStatus, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelStatus, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_ScreenBoot = ui_ScreenBoot;
uic_LabelWetter = ui_LabelWetter;
uic_LabelCube = ui_LabelCube;
uic_LabelAuthor = ui_LabelAuthor;
uic_BarWifi = ui_BarWifi;
uic_LabelStatus = ui_LabelStatus;

}

void ui_ScreenBoot_screen_destroy(void)
{
   if (ui_ScreenBoot) lv_obj_del(ui_ScreenBoot);

// NULL screen variables
uic_ScreenBoot= NULL;
ui_ScreenBoot= NULL;
uic_LabelWetter= NULL;
ui_LabelWetter= NULL;
uic_LabelCube= NULL;
ui_LabelCube= NULL;
uic_LabelAuthor= NULL;
ui_LabelAuthor= NULL;
uic_BarWifi= NULL;
ui_BarWifi= NULL;
uic_LabelStatus= NULL;
ui_LabelStatus= NULL;

}
