// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#include "ui.h"

lv_obj_t *uic_dayclear;
lv_obj_t *uic_snow;
lv_obj_t *uic_overcast;
lv_obj_t *uic_fog;
lv_obj_t *uic_thunder;
lv_obj_t *uic_rain;
lv_obj_t *uic_ScreenLager;
lv_obj_t *ui_ScreenLager = NULL;lv_obj_t *ui_rain = NULL;lv_obj_t *ui_thunder = NULL;lv_obj_t *ui_fog = NULL;lv_obj_t *ui_overcast = NULL;lv_obj_t *ui_snow = NULL;lv_obj_t *ui_dayclear = NULL;
// event funtions

// build funtions

void ui_ScreenLager_screen_init(void)
{
ui_ScreenLager = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenLager, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_rain = lv_img_create(ui_ScreenLager);
lv_img_set_src(ui_rain, &ui_img_rain_png);
lv_obj_set_width( ui_rain, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_rain, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_rain, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_rain, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_rain, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_thunder = lv_img_create(ui_ScreenLager);
lv_img_set_src(ui_thunder, &ui_img_thunder_png);
lv_obj_set_width( ui_thunder, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_thunder, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_thunder, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_thunder, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_thunder, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_fog = lv_img_create(ui_ScreenLager);
lv_img_set_src(ui_fog, &ui_img_fog_png);
lv_obj_set_width( ui_fog, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fog, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_fog, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_fog, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_fog, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_overcast = lv_img_create(ui_ScreenLager);
lv_img_set_src(ui_overcast, &ui_img_overcast_png);
lv_obj_set_width( ui_overcast, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_overcast, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_overcast, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_overcast, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_overcast, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_snow = lv_img_create(ui_ScreenLager);
lv_img_set_src(ui_snow, &ui_img_snow_png);
lv_obj_set_width( ui_snow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_snow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_snow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_snow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_snow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_dayclear = lv_img_create(ui_ScreenLager);
lv_img_set_src(ui_dayclear, &ui_img_day_clear_png);
lv_obj_set_width( ui_dayclear, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dayclear, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dayclear, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dayclear, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_dayclear, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

uic_ScreenLager = ui_ScreenLager;
uic_rain = ui_rain;
uic_thunder = ui_thunder;
uic_fog = ui_fog;
uic_overcast = ui_overcast;
uic_snow = ui_snow;
uic_dayclear = ui_dayclear;

}

void ui_ScreenLager_screen_destroy(void)
{
   if (ui_ScreenLager) lv_obj_del(ui_ScreenLager);

// NULL screen variables
uic_ScreenLager= NULL;
ui_ScreenLager= NULL;
uic_rain= NULL;
ui_rain= NULL;
uic_thunder= NULL;
ui_thunder= NULL;
uic_fog= NULL;
ui_fog= NULL;
uic_overcast= NULL;
ui_overcast= NULL;
uic_snow= NULL;
ui_snow= NULL;
uic_dayclear= NULL;
ui_dayclear= NULL;

}
