// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#include "ui.h"

lv_obj_t *uic_uiLabelDatum;
lv_obj_t *uic_LabelHum;
lv_obj_t *uic_ImageWetter;
lv_obj_t *uic_LabelTemp;
lv_obj_t *uic_LabelUhr;
lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_LabelUhr = NULL;lv_obj_t *ui_LabelTemp = NULL;lv_obj_t *ui_ImageWetter = NULL;lv_obj_t *ui_LabelHum = NULL;lv_obj_t *ui_uiLabelDatum = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Image2 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelUhr = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelUhr, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelUhr, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelUhr, 0 );
lv_obj_set_y( ui_LabelUhr, -73 );
lv_obj_set_align( ui_LabelUhr, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelUhr,"15:05");
lv_obj_set_style_text_color(ui_LabelUhr, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelUhr, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_LabelUhr, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_LabelUhr, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelUhr, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTemp = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTemp, -7 );
lv_obj_set_y( ui_LabelTemp, 68 );
lv_obj_set_align( ui_LabelTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTemp,"22° C");
lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTemp, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageWetter = lv_img_create(ui_Screen1);
lv_img_set_src(ui_ImageWetter, &ui_img_day_clear_png);
lv_obj_set_width( ui_ImageWetter, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageWetter, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageWetter, -80 );
lv_obj_set_y( ui_ImageWetter, 68 );
lv_obj_set_align( ui_ImageWetter, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageWetter, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageWetter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelHum = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_LabelHum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHum, 79 );
lv_obj_set_y( ui_LabelHum, 68 );
lv_obj_set_align( ui_LabelHum, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHum,"58 %");
lv_obj_set_style_text_color(ui_LabelHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHum, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uiLabelDatum = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_uiLabelDatum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uiLabelDatum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uiLabelDatum, -1 );
lv_obj_set_y( ui_uiLabelDatum, -14 );
lv_obj_set_align( ui_uiLabelDatum, LV_ALIGN_CENTER );
lv_label_set_text(ui_uiLabelDatum,"Mi. 20.05.2026");
lv_obj_set_style_text_color(ui_uiLabelDatum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_uiLabelDatum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_uiLabelDatum, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_1328666373);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, -7 );
lv_obj_set_y( ui_Image1, 35 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,140);

ui_Image2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image2, &ui_img_279934287);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, 79 );
lv_obj_set_y( ui_Image2, 35 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,140);

uic_LabelUhr = ui_LabelUhr;
uic_LabelTemp = ui_LabelTemp;
uic_ImageWetter = ui_ImageWetter;
uic_LabelHum = ui_LabelHum;
uic_uiLabelDatum = ui_uiLabelDatum;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
uic_LabelUhr= NULL;
ui_LabelUhr= NULL;
uic_LabelTemp= NULL;
ui_LabelTemp= NULL;
uic_ImageWetter= NULL;
ui_ImageWetter= NULL;
uic_LabelHum= NULL;
ui_LabelHum= NULL;
uic_uiLabelDatum= NULL;
ui_uiLabelDatum= NULL;
ui_Image1= NULL;
ui_Image2= NULL;

}
