// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#include "ui.h"

lv_obj_t *uic_LabelErleWert;
lv_obj_t *uic_LabelBeifussWert;
lv_obj_t *uic_LabelAmbrosiaWert;
lv_obj_t *uic_LabelGraeserWert;
lv_obj_t *uic_LabelBirkeWert;
lv_obj_t *uic_LabelNameAmbrosia;
lv_obj_t *uic_LabelNameErle;
lv_obj_t *uic_LabelNameGraeser;
lv_obj_t *uic_LabelNameBeifuss;
lv_obj_t *uic_TextAreaPollen;
lv_obj_t *uic_LabelNameBirke;
lv_obj_t *uic_ScreenPollen;
lv_obj_t *ui_ScreenPollen = NULL;lv_obj_t *ui_LabelNameBirke = NULL;lv_obj_t *ui_TextAreaPollen = NULL;lv_obj_t *ui_LabelNameBeifuss = NULL;lv_obj_t *ui_LabelNameGraeser = NULL;lv_obj_t *ui_LabelNameErle = NULL;lv_obj_t *ui_LabelNameAmbrosia = NULL;lv_obj_t *ui_LabelBirkeWert = NULL;lv_obj_t *ui_LabelGraeserWert = NULL;lv_obj_t *ui_LabelAmbrosiaWert = NULL;lv_obj_t *ui_LabelBeifussWert = NULL;lv_obj_t *ui_LabelErleWert = NULL;
// event funtions

// build funtions

void ui_ScreenPollen_screen_init(void)
{
ui_ScreenPollen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenPollen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenPollen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenPollen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNameBirke = lv_label_create(ui_ScreenPollen);
lv_obj_set_width( ui_LabelNameBirke, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNameBirke, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNameBirke, -74 );
lv_obj_set_y( ui_LabelNameBirke, -58 );
lv_obj_set_align( ui_LabelNameBirke, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNameBirke,"Birke");
lv_obj_set_scrollbar_mode(ui_LabelNameBirke, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelNameBirke, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelNameBirke, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelNameBirke, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelNameBirke, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaPollen = lv_textarea_create(ui_ScreenPollen);
lv_obj_set_width( ui_TextAreaPollen, 150);
lv_obj_set_height( ui_TextAreaPollen, 39);
lv_obj_set_x( ui_TextAreaPollen, 0 );
lv_obj_set_y( ui_TextAreaPollen, -102 );
lv_obj_set_align( ui_TextAreaPollen, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextAreaPollen,"Pollenflug");
lv_textarea_set_placeholder_text(ui_TextAreaPollen,"Placeholder...");
lv_obj_set_scrollbar_mode(ui_TextAreaPollen, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_TextAreaPollen, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextAreaPollen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextAreaPollen, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextAreaPollen, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextAreaPollen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextAreaPollen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextAreaPollen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextAreaPollen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_TextAreaPollen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TextAreaPollen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNameBeifuss = lv_label_create(ui_ScreenPollen);
lv_obj_set_width( ui_LabelNameBeifuss, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNameBeifuss, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNameBeifuss, -74 );
lv_obj_set_y( ui_LabelNameBeifuss, 47 );
lv_obj_set_align( ui_LabelNameBeifuss, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNameBeifuss,"Beifuss");
lv_obj_set_scrollbar_mode(ui_LabelNameBeifuss, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelNameBeifuss, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelNameBeifuss, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelNameBeifuss, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelNameBeifuss, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNameGraeser = lv_label_create(ui_ScreenPollen);
lv_obj_set_width( ui_LabelNameGraeser, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNameGraeser, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNameGraeser, -74 );
lv_obj_set_y( ui_LabelNameGraeser, -23 );
lv_obj_set_align( ui_LabelNameGraeser, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNameGraeser,"Graeser");
lv_obj_set_scrollbar_mode(ui_LabelNameGraeser, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelNameGraeser, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelNameGraeser, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelNameGraeser, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelNameGraeser, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNameErle = lv_label_create(ui_ScreenPollen);
lv_obj_set_width( ui_LabelNameErle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNameErle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNameErle, -74 );
lv_obj_set_y( ui_LabelNameErle, 12 );
lv_obj_set_align( ui_LabelNameErle, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNameErle,"Erle");
lv_obj_set_scrollbar_mode(ui_LabelNameErle, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelNameErle, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelNameErle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelNameErle, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelNameErle, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNameAmbrosia = lv_label_create(ui_ScreenPollen);
lv_obj_set_width( ui_LabelNameAmbrosia, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelNameAmbrosia, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNameAmbrosia, -74 );
lv_obj_set_y( ui_LabelNameAmbrosia, 82 );
lv_obj_set_align( ui_LabelNameAmbrosia, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNameAmbrosia,"Ambrosia");
lv_obj_set_scrollbar_mode(ui_LabelNameAmbrosia, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelNameAmbrosia, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelNameAmbrosia, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelNameAmbrosia, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelNameAmbrosia, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBirkeWert = lv_label_create(ui_ScreenPollen);
lv_obj_set_width( ui_LabelBirkeWert, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBirkeWert, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelBirkeWert, 59 );
lv_obj_set_y( ui_LabelBirkeWert, -58 );
lv_obj_set_align( ui_LabelBirkeWert, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBirkeWert,"--");
lv_obj_set_scrollbar_mode(ui_LabelBirkeWert, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelBirkeWert, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBirkeWert, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelBirkeWert, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBirkeWert, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelGraeserWert = lv_label_create(ui_ScreenPollen);
lv_obj_set_width( ui_LabelGraeserWert, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelGraeserWert, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelGraeserWert, 59 );
lv_obj_set_y( ui_LabelGraeserWert, -23 );
lv_obj_set_align( ui_LabelGraeserWert, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelGraeserWert,"--");
lv_obj_set_scrollbar_mode(ui_LabelGraeserWert, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelGraeserWert, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelGraeserWert, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelGraeserWert, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelGraeserWert, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAmbrosiaWert = lv_label_create(ui_ScreenPollen);
lv_obj_set_width( ui_LabelAmbrosiaWert, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAmbrosiaWert, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelAmbrosiaWert, 59 );
lv_obj_set_y( ui_LabelAmbrosiaWert, 82 );
lv_obj_set_align( ui_LabelAmbrosiaWert, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAmbrosiaWert,"--");
lv_obj_set_scrollbar_mode(ui_LabelAmbrosiaWert, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelAmbrosiaWert, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelAmbrosiaWert, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelAmbrosiaWert, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelAmbrosiaWert, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBeifussWert = lv_label_create(ui_ScreenPollen);
lv_obj_set_width( ui_LabelBeifussWert, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelBeifussWert, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelBeifussWert, 59 );
lv_obj_set_y( ui_LabelBeifussWert, 47 );
lv_obj_set_align( ui_LabelBeifussWert, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBeifussWert,"--");
lv_obj_set_scrollbar_mode(ui_LabelBeifussWert, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelBeifussWert, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelBeifussWert, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelBeifussWert, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelBeifussWert, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelErleWert = lv_label_create(ui_ScreenPollen);
lv_obj_set_width( ui_LabelErleWert, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelErleWert, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelErleWert, 59 );
lv_obj_set_y( ui_LabelErleWert, 12 );
lv_obj_set_align( ui_LabelErleWert, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelErleWert,"--");
lv_obj_set_scrollbar_mode(ui_LabelErleWert, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelErleWert, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelErleWert, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelErleWert, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelErleWert, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_ScreenPollen = ui_ScreenPollen;
uic_LabelNameBirke = ui_LabelNameBirke;
uic_TextAreaPollen = ui_TextAreaPollen;
uic_LabelNameBeifuss = ui_LabelNameBeifuss;
uic_LabelNameGraeser = ui_LabelNameGraeser;
uic_LabelNameErle = ui_LabelNameErle;
uic_LabelNameAmbrosia = ui_LabelNameAmbrosia;
uic_LabelBirkeWert = ui_LabelBirkeWert;
uic_LabelGraeserWert = ui_LabelGraeserWert;
uic_LabelAmbrosiaWert = ui_LabelAmbrosiaWert;
uic_LabelBeifussWert = ui_LabelBeifussWert;
uic_LabelErleWert = ui_LabelErleWert;

}

void ui_ScreenPollen_screen_destroy(void)
{
   if (ui_ScreenPollen) lv_obj_del(ui_ScreenPollen);

// NULL screen variables
uic_ScreenPollen= NULL;
ui_ScreenPollen= NULL;
uic_LabelNameBirke= NULL;
ui_LabelNameBirke= NULL;
uic_TextAreaPollen= NULL;
ui_TextAreaPollen= NULL;
uic_LabelNameBeifuss= NULL;
ui_LabelNameBeifuss= NULL;
uic_LabelNameGraeser= NULL;
ui_LabelNameGraeser= NULL;
uic_LabelNameErle= NULL;
ui_LabelNameErle= NULL;
uic_LabelNameAmbrosia= NULL;
ui_LabelNameAmbrosia= NULL;
uic_LabelBirkeWert= NULL;
ui_LabelBirkeWert= NULL;
uic_LabelGraeserWert= NULL;
ui_LabelGraeserWert= NULL;
uic_LabelAmbrosiaWert= NULL;
ui_LabelAmbrosiaWert= NULL;
uic_LabelBeifussWert= NULL;
ui_LabelBeifussWert= NULL;
uic_LabelErleWert= NULL;
ui_LabelErleWert= NULL;

}
