// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t *ui_Screen4;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_LabelH1Zeit;
extern lv_obj_t *ui_ImageH1;
extern lv_obj_t *ui_LabelH1Temp;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_LabelH2Zeit;
extern lv_obj_t *ui_ImageH2;
extern lv_obj_t *ui_LabelH2Temp;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_LabelH3Zeit;
extern lv_obj_t *ui_ImageH3;
extern lv_obj_t *ui_LabelH3Temp;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Screen4;
extern lv_obj_t *uic_LabelH1Zeit;
extern lv_obj_t *uic_ImageH1;
extern lv_obj_t *uic_LabelH1Temp;
extern lv_obj_t *uic_LabelH2Zeit;
extern lv_obj_t *uic_ImageH2;
extern lv_obj_t *uic_LabelH2Temp;
extern lv_obj_t *uic_LabelH3Zeit;
extern lv_obj_t *uic_ImageH3;
extern lv_obj_t *uic_LabelH3Temp;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

