// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#ifndef UI_SCREENPOLLEN_H
#define UI_SCREENPOLLEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPollen
extern void ui_ScreenPollen_screen_init(void);
extern void ui_ScreenPollen_screen_destroy(void);
extern lv_obj_t *ui_ScreenPollen;
extern lv_obj_t *ui_LabelNameBirke;
extern lv_obj_t *ui_TextAreaPollen;
extern lv_obj_t *ui_LabelNameBeifuss;
extern lv_obj_t *ui_LabelNameGraeser;
extern lv_obj_t *ui_LabelNameErle;
extern lv_obj_t *ui_LabelNameAmbrosia;
extern lv_obj_t *ui_LabelBirkeWert;
extern lv_obj_t *ui_LabelGraeserWert;
extern lv_obj_t *ui_LabelAmbrosiaWert;
extern lv_obj_t *ui_LabelBeifussWert;
extern lv_obj_t *ui_LabelErleWert;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenPollen;
extern lv_obj_t *uic_LabelNameBirke;
extern lv_obj_t *uic_TextAreaPollen;
extern lv_obj_t *uic_LabelNameBeifuss;
extern lv_obj_t *uic_LabelNameGraeser;
extern lv_obj_t *uic_LabelNameErle;
extern lv_obj_t *uic_LabelNameAmbrosia;
extern lv_obj_t *uic_LabelBirkeWert;
extern lv_obj_t *uic_LabelGraeserWert;
extern lv_obj_t *uic_LabelAmbrosiaWert;
extern lv_obj_t *uic_LabelBeifussWert;
extern lv_obj_t *uic_LabelErleWert;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

