// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t *ui_Screen2;
extern lv_obj_t *ui_LabelWind;
extern lv_obj_t *ui_LabelPress;
extern lv_obj_t *ui_LabelFeelsLike;
extern lv_obj_t *ui_TextArea3;
extern lv_obj_t *ui_TextArea4;
extern lv_obj_t *ui_TextArea5;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Screen2;
extern lv_obj_t *uic_LabelWind;
extern lv_obj_t *uic_LabelPress;
extern lv_obj_t *uic_LabelFeelsLike;
extern lv_obj_t *uic_TextArea3;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

