// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#include "ui.h"

lv_obj_t *uic_LabelH3Temp;
lv_obj_t *uic_ImageH3;
lv_obj_t *uic_LabelH3Zeit;
lv_obj_t *uic_LabelH2Temp;
lv_obj_t *uic_ImageH2;
lv_obj_t *uic_LabelH2Zeit;
lv_obj_t *uic_LabelH1Temp;
lv_obj_t *uic_ImageH1;
lv_obj_t *uic_LabelH1Zeit;
lv_obj_t *uic_Screen4;
lv_obj_t *ui_Screen4 = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_LabelH1Zeit = NULL;lv_obj_t *ui_ImageH1 = NULL;lv_obj_t *ui_LabelH1Temp = NULL;lv_obj_t *ui_Container2 = NULL;lv_obj_t *ui_LabelH2Zeit = NULL;lv_obj_t *ui_ImageH2 = NULL;lv_obj_t *ui_LabelH2Temp = NULL;lv_obj_t *ui_Container3 = NULL;lv_obj_t *ui_LabelH3Zeit = NULL;lv_obj_t *ui_ImageH3 = NULL;lv_obj_t *ui_LabelH3Temp = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
ui_Screen4 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Screen4);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 215);
lv_obj_set_height( ui_Container1, 69);
lv_obj_set_x( ui_Container1, 0 );
lv_obj_set_y( ui_Container1, -80 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Container1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container1, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Container1, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelH1Zeit = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_LabelH1Zeit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelH1Zeit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelH1Zeit, -67 );
lv_obj_set_y( ui_LabelH1Zeit, -80 );
lv_obj_set_align( ui_LabelH1Zeit, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelH1Zeit,"12:00");
lv_obj_set_scrollbar_mode(ui_LabelH1Zeit, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelH1Zeit, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelH1Zeit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelH1Zeit, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageH1 = lv_img_create(ui_Screen4);
lv_obj_set_width( ui_ImageH1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageH1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageH1, 0 );
lv_obj_set_y( ui_ImageH1, -80 );
lv_obj_set_align( ui_ImageH1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageH1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageH1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageH1,220);

ui_LabelH1Temp = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_LabelH1Temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelH1Temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelH1Temp, 70 );
lv_obj_set_y( ui_LabelH1Temp, -80 );
lv_obj_set_align( ui_LabelH1Temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelH1Temp,"15 °C");
lv_obj_set_scrollbar_mode(ui_LabelH1Temp, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelH1Temp, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelH1Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelH1Temp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_Screen4);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 215);
lv_obj_set_height( ui_Container2, 69);
lv_obj_set_x( ui_Container2, 0 );
lv_obj_set_y( ui_Container2, -3 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Container2, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelH2Zeit = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_LabelH2Zeit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelH2Zeit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelH2Zeit, -67 );
lv_obj_set_y( ui_LabelH2Zeit, -2 );
lv_obj_set_align( ui_LabelH2Zeit, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelH2Zeit,"12:00");
lv_obj_set_scrollbar_mode(ui_LabelH2Zeit, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelH2Zeit, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelH2Zeit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelH2Zeit, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageH2 = lv_img_create(ui_Screen4);
lv_obj_set_width( ui_ImageH2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageH2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageH2, 0 );
lv_obj_set_y( ui_ImageH2, -3 );
lv_obj_set_align( ui_ImageH2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageH2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageH2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageH2,220);

ui_LabelH2Temp = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_LabelH2Temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelH2Temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelH2Temp, 70 );
lv_obj_set_y( ui_LabelH2Temp, -2 );
lv_obj_set_align( ui_LabelH2Temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelH2Temp,"15 °C");
lv_obj_set_scrollbar_mode(ui_LabelH2Temp, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelH2Temp, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelH2Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelH2Temp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_Screen4);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, 215);
lv_obj_set_height( ui_Container3, 69);
lv_obj_set_x( ui_Container3, 0 );
lv_obj_set_y( ui_Container3, 75 );
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_Container3, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_border_width(ui_Container3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container3, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Container3, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelH3Zeit = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_LabelH3Zeit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelH3Zeit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelH3Zeit, -67 );
lv_obj_set_y( ui_LabelH3Zeit, 75 );
lv_obj_set_align( ui_LabelH3Zeit, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelH3Zeit,"12:00");
lv_obj_set_scrollbar_mode(ui_LabelH3Zeit, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelH3Zeit, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelH3Zeit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelH3Zeit, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageH3 = lv_img_create(ui_Screen4);
lv_obj_set_width( ui_ImageH3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageH3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageH3, 0 );
lv_obj_set_y( ui_ImageH3, 76 );
lv_obj_set_align( ui_ImageH3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageH3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageH3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageH3,220);

ui_LabelH3Temp = lv_label_create(ui_Screen4);
lv_obj_set_width( ui_LabelH3Temp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelH3Temp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelH3Temp, 70 );
lv_obj_set_y( ui_LabelH3Temp, 77 );
lv_obj_set_align( ui_LabelH3Temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelH3Temp,"15 °C");
lv_obj_set_scrollbar_mode(ui_LabelH3Temp, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelH3Temp, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelH3Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelH3Temp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_Screen4 = ui_Screen4;
uic_LabelH1Zeit = ui_LabelH1Zeit;
uic_ImageH1 = ui_ImageH1;
uic_LabelH1Temp = ui_LabelH1Temp;
uic_LabelH2Zeit = ui_LabelH2Zeit;
uic_ImageH2 = ui_ImageH2;
uic_LabelH2Temp = ui_LabelH2Temp;
uic_LabelH3Zeit = ui_LabelH3Zeit;
uic_ImageH3 = ui_ImageH3;
uic_LabelH3Temp = ui_LabelH3Temp;

}

void ui_Screen4_screen_destroy(void)
{
   if (ui_Screen4) lv_obj_del(ui_Screen4);

// NULL screen variables
uic_Screen4= NULL;
ui_Screen4= NULL;
ui_Container1= NULL;
uic_LabelH1Zeit= NULL;
ui_LabelH1Zeit= NULL;
uic_ImageH1= NULL;
ui_ImageH1= NULL;
uic_LabelH1Temp= NULL;
ui_LabelH1Temp= NULL;
ui_Container2= NULL;
uic_LabelH2Zeit= NULL;
ui_LabelH2Zeit= NULL;
uic_ImageH2= NULL;
ui_ImageH2= NULL;
uic_LabelH2Temp= NULL;
ui_LabelH2Temp= NULL;
ui_Container3= NULL;
uic_LabelH3Zeit= NULL;
ui_LabelH3Zeit= NULL;
uic_ImageH3= NULL;
ui_ImageH3= NULL;
uic_LabelH3Temp= NULL;
ui_LabelH3Temp= NULL;

}
