// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#ifndef UI_SCREENLAGER_H
#define UI_SCREENLAGER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenLager
extern void ui_ScreenLager_screen_init(void);
extern void ui_ScreenLager_screen_destroy(void);
extern lv_obj_t *ui_ScreenLager;
extern lv_obj_t *ui_rain;
extern lv_obj_t *ui_thunder;
extern lv_obj_t *ui_fog;
extern lv_obj_t *ui_overcast;
extern lv_obj_t *ui_snow;
extern lv_obj_t *ui_dayclear;
// CUSTOM VARIABLES
extern lv_obj_t *uic_ScreenLager;
extern lv_obj_t *uic_rain;
extern lv_obj_t *uic_thunder;
extern lv_obj_t *uic_fog;
extern lv_obj_t *uic_overcast;
extern lv_obj_t *uic_snow;
extern lv_obj_t *uic_dayclear;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

