// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#include "ui.h"

lv_obj_t *uic_TextUv;
lv_obj_t *uic_TextSonnenuntergang;
lv_obj_t *uic_TextSonnenaufgang;
lv_obj_t *uic_LabelUV;
lv_obj_t *uic_LabelUntergang;
lv_obj_t *uic_LabelAufgang;
lv_obj_t *ui_Screen3 = NULL;lv_obj_t *ui_LabelAufgang = NULL;lv_obj_t *ui_LabelUntergang = NULL;lv_obj_t *ui_LabelUV = NULL;lv_obj_t *ui_TextSonnenaufgang = NULL;lv_obj_t *ui_TextSonnenuntergang = NULL;lv_obj_t *ui_TextUv = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAufgang = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_LabelAufgang, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelAufgang, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelAufgang, 0 );
lv_obj_set_y( ui_LabelAufgang, -62 );
lv_obj_set_align( ui_LabelAufgang, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAufgang,"12:00");
lv_obj_set_style_text_color(ui_LabelAufgang, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelAufgang, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelAufgang, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelUntergang = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_LabelUntergang, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelUntergang, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelUntergang, 0 );
lv_obj_set_y( ui_LabelUntergang, 15 );
lv_obj_set_align( ui_LabelUntergang, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelUntergang,"13:00");
lv_obj_set_style_text_color(ui_LabelUntergang, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelUntergang, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelUntergang, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelUV = lv_label_create(ui_Screen3);
lv_obj_set_width( ui_LabelUV, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelUV, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelUV, 0 );
lv_obj_set_y( ui_LabelUV, 90 );
lv_obj_set_align( ui_LabelUV, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelUV,"6");
lv_obj_set_style_text_color(ui_LabelUV, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelUV, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelUV, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelUV, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextSonnenaufgang = lv_textarea_create(ui_Screen3);
lv_obj_set_width( ui_TextSonnenaufgang, 240);
lv_obj_set_height( ui_TextSonnenaufgang, 40);
lv_obj_set_x( ui_TextSonnenaufgang, 0 );
lv_obj_set_y( ui_TextSonnenaufgang, -98 );
lv_obj_set_align( ui_TextSonnenaufgang, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextSonnenaufgang,"Sonnenaufgang");
lv_textarea_set_placeholder_text(ui_TextSonnenaufgang,"Placeholder...");
lv_obj_set_scrollbar_mode(ui_TextSonnenaufgang, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_TextSonnenaufgang, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextSonnenaufgang, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextSonnenaufgang, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextSonnenaufgang, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextSonnenaufgang, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextSonnenaufgang, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextSonnenaufgang, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextSonnenaufgang, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextSonnenuntergang = lv_textarea_create(ui_Screen3);
lv_obj_set_width( ui_TextSonnenuntergang, 240);
lv_obj_set_height( ui_TextSonnenuntergang, 40);
lv_obj_set_x( ui_TextSonnenuntergang, 0 );
lv_obj_set_y( ui_TextSonnenuntergang, -21 );
lv_obj_set_align( ui_TextSonnenuntergang, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextSonnenuntergang,"Sonnenuntergang");
lv_textarea_set_placeholder_text(ui_TextSonnenuntergang,"Placeholder...");
lv_obj_set_scrollbar_mode(ui_TextSonnenuntergang, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_TextSonnenuntergang, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextSonnenuntergang, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextSonnenuntergang, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextSonnenuntergang, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextSonnenuntergang, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextSonnenuntergang, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextSonnenuntergang, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextSonnenuntergang, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextUv = lv_textarea_create(ui_Screen3);
lv_obj_set_width( ui_TextUv, 240);
lv_obj_set_height( ui_TextUv, 40);
lv_obj_set_x( ui_TextUv, 0 );
lv_obj_set_y( ui_TextUv, 54 );
lv_obj_set_align( ui_TextUv, LV_ALIGN_CENTER );
lv_textarea_set_text(ui_TextUv,"UV Index");
lv_textarea_set_placeholder_text(ui_TextUv,"Placeholder...");
lv_obj_set_scrollbar_mode(ui_TextUv, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_TextUv, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextUv, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TextUv, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextUv, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextUv, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextUv, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextUv, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextUv, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_LabelAufgang = ui_LabelAufgang;
uic_LabelUntergang = ui_LabelUntergang;
uic_LabelUV = ui_LabelUV;
uic_TextSonnenaufgang = ui_TextSonnenaufgang;
uic_TextSonnenuntergang = ui_TextSonnenuntergang;
uic_TextUv = ui_TextUv;

}

void ui_Screen3_screen_destroy(void)
{
   if (ui_Screen3) lv_obj_del(ui_Screen3);

// NULL screen variables
ui_Screen3= NULL;
uic_LabelAufgang= NULL;
ui_LabelAufgang= NULL;
uic_LabelUntergang= NULL;
ui_LabelUntergang= NULL;
uic_LabelUV= NULL;
ui_LabelUV= NULL;
uic_TextSonnenaufgang= NULL;
ui_TextSonnenaufgang= NULL;
uic_TextSonnenuntergang= NULL;
ui_TextSonnenuntergang= NULL;
uic_TextUv= NULL;
ui_TextUv= NULL;

}
