// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#include "ui.h"

lv_obj_t *uic_LabelWarnHint;
lv_obj_t *uic_LabelWarnDetail;
lv_obj_t *uic_LabelWarnTitel;
lv_obj_t *uic_ImageWarnRegen;
lv_obj_t *uic_uiScreenWarnung;
lv_obj_t *ui_uiScreenWarnung = NULL;lv_obj_t *ui_ImageWarnRegen = NULL;lv_obj_t *ui_LabelWarnTitel = NULL;lv_obj_t *ui_LabelWarnDetail = NULL;lv_obj_t *ui_LabelWarnHint = NULL;
// event funtions

// build funtions

void ui_uiScreenWarnung_screen_init(void)
{
ui_uiScreenWarnung = lv_obj_create(NULL);
lv_obj_clear_flag( ui_uiScreenWarnung, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_uiScreenWarnung, lv_color_hex(0xCC0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uiScreenWarnung, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageWarnRegen = lv_img_create(ui_uiScreenWarnung);
lv_img_set_src(ui_ImageWarnRegen, &ui_img_rain_80x80_png);
lv_obj_set_width( ui_ImageWarnRegen, LV_SIZE_CONTENT);  /// 80
lv_obj_set_height( ui_ImageWarnRegen, LV_SIZE_CONTENT);   /// 80
lv_obj_set_x( ui_ImageWarnRegen, 0 );
lv_obj_set_y( ui_ImageWarnRegen, -75 );
lv_obj_set_align( ui_ImageWarnRegen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageWarnRegen, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageWarnRegen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelWarnTitel = lv_label_create(ui_uiScreenWarnung);
lv_obj_set_width( ui_LabelWarnTitel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWarnTitel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWarnTitel, 0 );
lv_obj_set_y( ui_LabelWarnTitel, -11 );
lv_obj_set_align( ui_LabelWarnTitel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWarnTitel,"Regenwarnung!");
lv_obj_set_scrollbar_mode(ui_LabelWarnTitel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelWarnTitel, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWarnTitel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelWarnTitel, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWarnDetail = lv_label_create(ui_uiScreenWarnung);
lv_obj_set_width( ui_LabelWarnDetail, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWarnDetail, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWarnDetail, 0 );
lv_obj_set_y( ui_LabelWarnDetail, 29 );
lv_obj_set_align( ui_LabelWarnDetail, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWarnDetail,"Regen in den naechsten\n               60 Min.");
lv_obj_set_scrollbar_mode(ui_LabelWarnDetail, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelWarnDetail, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWarnDetail, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelWarnDetail, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelWarnDetail, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWarnHint = lv_label_create(ui_uiScreenWarnung);
lv_obj_set_width( ui_LabelWarnHint, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWarnHint, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWarnHint, 0 );
lv_obj_set_y( ui_LabelWarnHint, 81 );
lv_obj_set_align( ui_LabelWarnHint, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWarnHint,"Tippen zum Bestaetigen");
lv_obj_set_scrollbar_mode(ui_LabelWarnHint, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelWarnHint, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWarnHint, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelWarnHint, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelWarnHint, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_uiScreenWarnung = ui_uiScreenWarnung;
uic_ImageWarnRegen = ui_ImageWarnRegen;
uic_LabelWarnTitel = ui_LabelWarnTitel;
uic_LabelWarnDetail = ui_LabelWarnDetail;
uic_LabelWarnHint = ui_LabelWarnHint;

}

void ui_uiScreenWarnung_screen_destroy(void)
{
   if (ui_uiScreenWarnung) lv_obj_del(ui_uiScreenWarnung);

// NULL screen variables
uic_uiScreenWarnung= NULL;
ui_uiScreenWarnung= NULL;
uic_ImageWarnRegen= NULL;
ui_ImageWarnRegen= NULL;
uic_LabelWarnTitel= NULL;
ui_LabelWarnTitel= NULL;
uic_LabelWarnDetail= NULL;
ui_LabelWarnDetail= NULL;
uic_LabelWarnHint= NULL;
ui_LabelWarnHint= NULL;

}
