// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#include "ui.h"

lv_obj_t *uic_LabelPollenWarnHint;
lv_obj_t *uic_LabelPollenWarnArt;
lv_obj_t *uic_LabelPollenWarnTitel;
lv_obj_t *uic_ImageWarnPollen;
lv_obj_t *uic_uiScreenWarnungPollen;
lv_obj_t *ui_uiScreenWarnungPollen = NULL;lv_obj_t *ui_ImageWarnPollen = NULL;lv_obj_t *ui_LabelPollenWarnTitel = NULL;lv_obj_t *ui_LabelPollenWarnArt = NULL;lv_obj_t *ui_LabelPollenWarnHint = NULL;
// event funtions

// build funtions

void ui_uiScreenWarnungPollen_screen_init(void)
{
ui_uiScreenWarnungPollen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_uiScreenWarnungPollen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_uiScreenWarnungPollen, lv_color_hex(0xCC0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_uiScreenWarnungPollen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageWarnPollen = lv_img_create(ui_uiScreenWarnungPollen);
lv_img_set_src(ui_ImageWarnPollen, &ui_img_alert_png);
lv_obj_set_width( ui_ImageWarnPollen, LV_SIZE_CONTENT);  /// 80
lv_obj_set_height( ui_ImageWarnPollen, LV_SIZE_CONTENT);   /// 80
lv_obj_set_x( ui_ImageWarnPollen, 0 );
lv_obj_set_y( ui_ImageWarnPollen, -75 );
lv_obj_set_align( ui_ImageWarnPollen, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageWarnPollen, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageWarnPollen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageWarnPollen,90);

ui_LabelPollenWarnTitel = lv_label_create(ui_uiScreenWarnungPollen);
lv_obj_set_width( ui_LabelPollenWarnTitel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPollenWarnTitel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPollenWarnTitel, 0 );
lv_obj_set_y( ui_LabelPollenWarnTitel, -11 );
lv_obj_set_align( ui_LabelPollenWarnTitel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPollenWarnTitel,"Pollenwarnung!");
lv_obj_set_scrollbar_mode(ui_LabelPollenWarnTitel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelPollenWarnTitel, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPollenWarnTitel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPollenWarnTitel, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPollenWarnArt = lv_label_create(ui_uiScreenWarnungPollen);
lv_obj_set_width( ui_LabelPollenWarnArt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPollenWarnArt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPollenWarnArt, 0 );
lv_obj_set_y( ui_LabelPollenWarnArt, 29 );
lv_obj_set_align( ui_LabelPollenWarnArt, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPollenWarnArt,"---");
lv_obj_set_scrollbar_mode(ui_LabelPollenWarnArt, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelPollenWarnArt, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPollenWarnArt, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelPollenWarnArt, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPollenWarnArt, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPollenWarnHint = lv_label_create(ui_uiScreenWarnungPollen);
lv_obj_set_width( ui_LabelPollenWarnHint, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPollenWarnHint, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPollenWarnHint, 0 );
lv_obj_set_y( ui_LabelPollenWarnHint, 81 );
lv_obj_set_align( ui_LabelPollenWarnHint, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPollenWarnHint,"Tippen zum Bestaetigen");
lv_obj_set_scrollbar_mode(ui_LabelPollenWarnHint, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_LabelPollenWarnHint, lv_color_hex(0xECE0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPollenWarnHint, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelPollenWarnHint, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPollenWarnHint, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_uiScreenWarnungPollen = ui_uiScreenWarnungPollen;
uic_ImageWarnPollen = ui_ImageWarnPollen;
uic_LabelPollenWarnTitel = ui_LabelPollenWarnTitel;
uic_LabelPollenWarnArt = ui_LabelPollenWarnArt;
uic_LabelPollenWarnHint = ui_LabelPollenWarnHint;

}

void ui_uiScreenWarnungPollen_screen_destroy(void)
{
   if (ui_uiScreenWarnungPollen) lv_obj_del(ui_uiScreenWarnungPollen);

// NULL screen variables
uic_uiScreenWarnungPollen= NULL;
ui_uiScreenWarnungPollen= NULL;
uic_ImageWarnPollen= NULL;
ui_ImageWarnPollen= NULL;
uic_LabelPollenWarnTitel= NULL;
ui_LabelPollenWarnTitel= NULL;
uic_LabelPollenWarnArt= NULL;
ui_LabelPollenWarnArt= NULL;
uic_LabelPollenWarnHint= NULL;
ui_LabelPollenWarnHint= NULL;

}
