// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#ifndef UI_UISCREENWARNUNGPOLLEN_H
#define UI_UISCREENWARNUNGPOLLEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uiScreenWarnungPollen
extern void ui_uiScreenWarnungPollen_screen_init(void);
extern void ui_uiScreenWarnungPollen_screen_destroy(void);
extern lv_obj_t *ui_uiScreenWarnungPollen;
extern lv_obj_t *ui_ImageWarnPollen;
extern lv_obj_t *ui_LabelPollenWarnTitel;
extern lv_obj_t *ui_LabelPollenWarnArt;
extern lv_obj_t *ui_LabelPollenWarnHint;
// CUSTOM VARIABLES
extern lv_obj_t *uic_uiScreenWarnungPollen;
extern lv_obj_t *uic_ImageWarnPollen;
extern lv_obj_t *uic_LabelPollenWarnTitel;
extern lv_obj_t *uic_LabelPollenWarnArt;
extern lv_obj_t *uic_LabelPollenWarnHint;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

