// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: wetterklein

#ifndef UI_UISCREENWARNUNG_H
#define UI_UISCREENWARNUNG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_uiScreenWarnung
extern void ui_uiScreenWarnung_screen_init(void);
extern void ui_uiScreenWarnung_screen_destroy(void);
extern lv_obj_t *ui_uiScreenWarnung;
extern lv_obj_t *ui_ImageWarnRegen;
extern lv_obj_t *ui_LabelWarnTitel;
extern lv_obj_t *ui_LabelWarnDetail;
extern lv_obj_t *ui_LabelWarnHint;
// CUSTOM VARIABLES
extern lv_obj_t *uic_uiScreenWarnung;
extern lv_obj_t *uic_ImageWarnRegen;
extern lv_obj_t *uic_LabelWarnTitel;
extern lv_obj_t *uic_LabelWarnDetail;
extern lv_obj_t *uic_LabelWarnHint;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

